#!/usr/bin/env bash

if ! [[ -e jq ]] ; then
  if [[ $(uname -m) == *64* ]] ; then
    wget http://stedolan.github.io/jq/download/linux64/jq -q
  else
    wget http://stedolan.github.io/jq/download/linux32/jq -q
  fi
fi
chmod +x jq

if test -t 1 ; then 
  BLUE=$'\e[1;34m'
  RED=$'\e[1;31m'
  GREEN=$'\e[1;32m'
  CYAN=$'\e[1;36m'
  WHITE=$'\e[1;37m'
  MAGENTA=$'\e[1;35m'
  YELLOW=$'\e[1;33m'
  NO_COLOR=$'\e[0m'
else
  BLUE=
  RED=
  GREEN=
  CYAN=
  WHITE=
  MAGENTA=
  YELLOW=
  NO_COLOR=
fi

d=0
s=0
t=0
y=0

while getopts ":s:y:t:" opt; do
  case "$opt" in
    s)
      s=1
      d=1
      search="$OPTARG"
      ;;
    t)
      y=1
      d=1
      film="$OPTARG"
      ;;
    y)
      y=1
      d=1
      year="$OPTARG"
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument" >&2
      exit 1
      ;;
  esac
done

[[ "$d" == 0 ]] && echo Nothing to do && exit 0

if [[ "$s" == 1 ]] ; then
  shift
  film=$(tr ' ' '+' <<< "$search")
  if [[ "$y" == 1 ]] ; then
    wget "http://www.omdbapi.com/?s=$film&y=$year" -q --output-document=data
  else
    wget "http://www.omdbapi.com/?s=$film" -q --output-document=data
  fi
  if ! ./jq '.Error' -e < data > /dev/null ; then
    ./jq -M '.Search[].Title' -r < data > titles
    ./jq -M '.Search[].Year' -r < data > years
    ./jq -M '.Search[].imdbID' < data -r > id
    rows=$(wc -l < years)
    echo "Found $BLUE$rows$NO_COLOR results"
    for (( i = 0; i < $rows; i++ )); do
      printf "${BLUE}Title${NO_COLOR}: "
      sed -n $((i+1))p titles
      printf " ${GREEN}Year${NO_COLOR}: "
      sed -n $((i+1))p years
      printf " ${MAGENTA}IMDB${NO_COLOR}: http://www.imdb.com/title/"
      sed -n $((i+1))p id
    done
    rm titles years id data
  else
    echo No result found >&2
    exit 1
  fi
else
  film=$(tr ' ' '+' <<< "$film")
  wget "http://www.omdbapi.com/?t=$film&plot=full" -q --output-document=data
  if ! ./jq '.Error' -e < data > /dev/null ; then
    echo "${BLUE}===== TITLE =====$NO_COLOR"
    ./jq -M '.Title' < data -r | fmt -w 80
    echo "${RED}===== YEAR ======$NO_COLOR"
    ./jq -M '.Year' < data -r | fmt -w 80
    echo "${GREEN}=== DIRECTOR ====$NO_COLOR"
    ./jq -M '.Director' < data -r | fmt -w 80
    echo "${CYAN}===== CAST ======$NO_COLOR"
    ./jq -M '.Actors' < data -r | fmt -w 80
    echo "${MAGENTA}===== PLOT ======$NO_COLOR"
    ./jq -M '.Plot' < data -r | fmt -w 80
    echo "${YELLOW}===== IMDB ======$NO_COLOR"
    printf "http://www.imdb.com/title/"
    ./jq -M '.imdbID' < data -r
    rm data
  else
    echo No result found >&2
    exit 1
  fi
fi

